# Generated by Django 3.2.16 on 2023-01-15 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=150, verbose_name='Breed name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=150, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=150, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Contact Message')),
            ],
        ),
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Puppy Name')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('img', models.ImageField(upload_to='', verbose_name='Puppy Featured Image')),
                ('dob', models.DateTimeField()),
                ('description', models.TextField(verbose_name='Post Contents')),
                ('price', models.IntegerField()),
                ('sire', models.CharField(max_length=150)),
                ('dam', models.CharField(max_length=150)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('health_vaccine', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Sold out', 'Sold out')], default='Available', max_length=10)),
                ('puppy_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.breed', verbose_name='Post Category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('name', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Puppy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='app.puppy')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
