# Generated by Django 3.2.16 on 2023-01-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='Puppy',
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='puppy_breed',
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Puppy',
        ),
    ]
