# Generated by Django 3.2.16 on 2023-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('service_type', models.CharField(max_length=50, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Contact Message')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
