# Generated by Django 3.2.16 on 2023-01-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_breed_contact_images_offer_puppy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='dob',
            field=models.DateField(),
        ),
    ]
