# Generated by Django 3.2.16 on 2023-02-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
