# Generated by Django 3.2.16 on 2023-02-04 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20230204_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=150, verbose_name='Breed name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Puppy Name')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('banner', models.ImageField(upload_to='puppy/banner', verbose_name='Puppy Featured Image')),
                ('dob', models.DateField()),
                ('description', models.TextField(verbose_name='Post Contents')),
                ('price', models.IntegerField()),
                ('sire', models.CharField(blank=True, max_length=150, null=True)),
                ('dam', models.CharField(blank=True, max_length=150, null=True)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('health_vaccine', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Sold out', 'Sold out')], default='Available', max_length=10)),
                ('puppy_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.breed', verbose_name='Post Category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Puppy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='app.puppy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='puppy/images')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('puppy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.puppy')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Contact Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Contact Message')),
                ('phone', models.TextField(verbose_name='Phone Number')),
                ('ever_own_pet', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Ever own a pet?')),
                ('ever_own_dog', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Ever own a dog?')),
                ('home_type', models.TextField(verbose_name='Type of home')),
                ('home_fenced', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Is your house fenced?')),
                ('puppy_home', models.CharField(choices=[('Inside', 'Inside'), ('Outside', 'Outside')], max_length=7, verbose_name='Will the puppy be housed inside or outside?')),
                ('care_taker', models.CharField(max_length=100, verbose_name='Who will be the primary caretaker of the dog?')),
                ('puppy_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any Gender', 'Any Gender')], max_length=10, verbose_name='Are you interested in a male or female puppy?')),
                ('about_yourself', models.TextField(verbose_name='Is there anything else that you would like to tell us about yourself and your family?')),
                ('question', models.TextField(verbose_name='Do you have any question for us?')),
                ('puppy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.puppy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
