# Generated by Django 3.2.16 on 2023-02-09 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_apply_breed_contact_images_offer_puppy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Category name')),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=200, verbose_name='Home Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150, verbose_name='Post Title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Post Featured Image')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('post_contents', models.TextField(verbose_name='Post Contents')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Publish')], default=0, null=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postcategory', verbose_name='Post Category')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
