# Generated by Django 3.2.16 on 2023-02-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_anonymouscontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='category_description',
        ),
    ]
