# Generated by Django 3.2.16 on 2023-02-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_postcategory_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='puppy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.blogpost'),
        ),
    ]
