# Generated by Django 3.2.16 on 2023-02-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_blogpost_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_title',
            new_name='title',
        ),
    ]
