# Generated by Django 3.2.16 on 2023-02-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_post_title_blogpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='blog/images')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('puppy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.blogpost')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
