# Generated by Django 3.2.16 on 2023-02-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_blogimages_puppy'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimages',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
