# Generated by Django 3.2.16 on 2023-02-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_blogimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='puppy_breed',
            field=models.CharField(choices=[('German Shepherd', 'German Shepherd'), ('Bulldog', 'Bulldog'), ('Labrador Retriever', 'Labrador Retriever'), ('Golden Retriever', 'Golden Retriever'), ('French Bulldog', 'French Bulldog'), ('Siberian Husky', 'Siberian Husky'), ('Poodle', 'Poodle'), ('Alaskan Malamute', 'Alaskan Malamute'), ('Chihuahua', 'Chihuahua'), ('Border Collie', 'Border Collie'), ('Afghan Hound', 'Afghan Hound'), ('Airedale Terrier', 'Airedale Terrier'), ('Dachshund', 'Dachshund'), ('Affenpinscher', 'Affenpinscher'), ('Rottweiler', 'Rottweiler'), ('American Eskimo Dog', 'American Eskimo Dog'), ('Bichon Frisé', 'Bichon Frisé'), ('Great Dane', 'Great Dane'), ('Maltese dog', 'Maltese dog'), ('Australian Shepherd', 'Australian Shepherd'), ('English Cocker Spaniel', 'English Cocker Spaniel'), ('Chow Chow', 'Chow Chow'), ('Pomeranian', 'Pomeranian'), ('Yorkshire Terrier', 'Yorkshire Terrier'), ('Pembroke Welsh Corgi', 'Pembroke Welsh Corgi'), ('Cavalier King Charles Spaniel', 'Cavalier King Charles Spaniel'), ('Anatolian Shepherd Dog', 'Anatolian Shepherd Dog'), ('Basset Hound', 'Basset Hound'), ('Newfoundland dog', 'Newfoundland dog'), ('Belgian Shepherd', 'Belgian Shepherd'), ('Basenji', 'Basenji'), ('Havanese', 'Havanese'), ('Brittany', 'Brittany'), ('Bullmastiff', 'Bullmastiff'), ('Boston Terrier', 'Boston Terrier'), ('Cairn Terrier', 'Cairn Terrier'), ('Sheltie', 'Sheltie'), ('Black Russian Terrier', 'Black Russian Terrier'), ('Bedlington Terrier', 'Bedlington Terrier'), ('American Pit Bull Terrier', 'American Pit Bull Terrier'), ('Dobermann', 'Dobermann'), ('Shiba Inu', 'Shiba Inu'), ('Shih Tzu', 'Shih Tzu'), ('Sarabi dog', 'Sarabi dog'), ('Samoyed', 'Samoyed'), ('Maltipoo', 'Maltipoo'), ('Jack Russell Terrier', 'Jack Russell Terrier'), ('Goldendoodle', 'Goldendoodle'), ('American Bully', 'American Bully'), ('Dalmatian', 'Dalmatian'), ('Akita Inu', 'Akita Inu')], max_length=29, verbose_name='Breed'),
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
