# Generated by Django 3.2.16 on 2023-02-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230209_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='puppy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.puppy'),
        ),
    ]
