# Generated by Django 3.2.16 on 2023-02-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_images_puppy'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
