# Generated by Django 3.2.16 on 2023-02-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_images_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='Puppy',
            new_name='puppy',
        ),
    ]
